/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Rio_TV_Stand: THREE.Mesh;
    Rio_TV_Stand_DESK: THREE.Mesh;
    Rio_TV_Stand_DESK001: THREE.Mesh;
    Rio_TV_Stand_DESK002: THREE.Mesh;
    Rio_TV_Stand_DESK003: THREE.Mesh;
  };
  materials: {
    FUNITURE_016_MAT: THREE.MeshStandardMaterial;
  };
};

export function RioShelf(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/rio_tv_stand.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Rio_TV_Stand_ROOT"
          userData={{ name: "Rio TV Stand_ROOT" }}
        >
          <mesh
            name="Rio_TV_Stand"
            castShadow
            receiveShadow
            geometry={nodes.Rio_TV_Stand.geometry}
            material={materials.FUNITURE_016_MAT}
            userData={{ name: "Rio TV Stand" }}
          />
          <mesh
            name="Rio_TV_Stand_DESK"
            castShadow
            receiveShadow
            geometry={nodes.Rio_TV_Stand_DESK.geometry}
            material={materials.FUNITURE_016_MAT}
            position={[-1.267, 0.231, 0.308]}
            userData={{ name: "Rio TV Stand_DESK" }}
          />
          <mesh
            name="Rio_TV_Stand_DESK001"
            castShadow
            receiveShadow
            geometry={nodes.Rio_TV_Stand_DESK001.geometry}
            material={materials.FUNITURE_016_MAT}
            position={[1.268, 0.231, 0.308]}
            userData={{ name: "Rio TV Stand_DESK.001" }}
          />
          <mesh
            name="Rio_TV_Stand_DESK002"
            castShadow
            receiveShadow
            geometry={nodes.Rio_TV_Stand_DESK002.geometry}
            material={materials.FUNITURE_016_MAT}
            position={[0.423, 0.231, 0.308]}
            userData={{ name: "Rio TV Stand_DESK.002" }}
          />
          <mesh
            name="Rio_TV_Stand_DESK003"
            castShadow
            receiveShadow
            geometry={nodes.Rio_TV_Stand_DESK003.geometry}
            material={materials.FUNITURE_016_MAT}
            position={[-0.422, 0.231, 0.308]}
            userData={{ name: "Rio TV Stand_DESK.003" }}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/rio_tv_stand.glb");
