/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Screen } from "@/components/Screen";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Antenna_connection: THREE.Mesh;
    BackSide: THREE.Mesh;
    Front_Screen_Frame: THREE.Mesh;
    HDMI_connection: THREE.Mesh;
    Main_Screen_Frame: THREE.Mesh;
    Screen: THREE.Mesh;
    Stand: THREE.Mesh;
  };
  materials: {
    Metal: THREE.MeshStandardMaterial;
    Plastic012B: THREE.MeshStandardMaterial;
    Plastic011: THREE.MeshStandardMaterial;
    Plastic006: THREE.MeshStandardMaterial;
    Screen: THREE.MeshStandardMaterial;
  };
};

export function Tv(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/Tv.glb") as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <mesh
        name="Antenna_connection"
        castShadow
        receiveShadow
        geometry={nodes.Antenna_connection.geometry}
        material={materials.Metal}
      />
      <mesh
        name="BackSide"
        castShadow
        receiveShadow
        geometry={nodes.BackSide.geometry}
        material={materials.Plastic012B}
      />
      <mesh
        name="Front_Screen_Frame"
        castShadow
        receiveShadow
        geometry={nodes.Front_Screen_Frame.geometry}
        material={materials.Plastic011}
        position={[0, 0.539, 0.029]}
      />
      <mesh
        name="HDMI_connection"
        castShadow
        receiveShadow
        geometry={nodes.HDMI_connection.geometry}
        material={materials.Metal}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        name="Main_Screen_Frame"
        castShadow
        receiveShadow
        geometry={nodes.Main_Screen_Frame.geometry}
        material={materials.Plastic006}
      />
      <mesh
        name="Screen"
        castShadow
        receiveShadow
        geometry={nodes.Screen.geometry}
        material={materials.Screen}
        position={[0, 0.539, 0.029]}
      >
        <Screen src={"/videoplayback.mp4"} />
      </mesh>
      <mesh
        name="Stand"
        castShadow
        receiveShadow
        geometry={nodes.Stand.geometry}
        material={materials.Plastic012B}
      />
    </group>
  );
}

useGLTF.preload("/models/Tv.glb");
